# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ZipMap' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  use_frameworks!

  # Pods for ZipMap

end
